ai4dlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views 
from users import urls as user_urls
from team import urls as team_urls
from home import urls as home_urls
from news import urls as news_urls
from blog import urls as blog_urls
from call import urls as call_urls
from colab import urls as colab_urls
from conference import urls as conference_urls
from dportal import urls as dportal_urls
from jupyinter import urls as jupyinter_urls
from partner import urls as partner_urls
from project import urls as project_urls
from publication import urls as publication_urls
from lab import urls as lab_urls
from workshop import urls as workshop_urls
from contact import urls as contact_urls
from sponsor import urls as sponsor_urls
from community import urls as community_urls
from learning import urls as learning_urls
from package import urls as package_urls
from users.forms import ConfirmResetForm
urlpatterns = [
    path('admin/', admin.site.urls),
    # include django browserable 
    path("auth-api/", include("rest_framework.urls", namespace="rest_framework")),
    # include django authentication 
    # path('accounts/', include('django.contrib.auth.urls'))
    path('', include(home_urls)),
    path('users/', include(user_urls)),
    path('team/', include(team_urls)),
    path('news/', include(news_urls)),
    path('blog/', include(blog_urls)),
    path('call/', include(call_urls)),
    path('colab/', include(colab_urls)),
    path('conference/', include(conference_urls)),
    path('workshop/', include(workshop_urls)),
    path('dportal/', include(dportal_urls)),
    path('jupyinter/', include(jupyinter_urls)),
    path('partner/', include(partner_urls)),
    path('project/', include(project_urls)),
    path('publication/', include(publication_urls)),
    path('lab/', include(lab_urls)),
    path('contact/', include(contact_urls)),
    path('sponsor/', include(sponsor_urls)),
    path('community/', include(community_urls)),
    path('learning/', include(learning_urls)),
    path('package/', include(package_urls)),
    # we can mention them this way
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=ConfirmResetForm, template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),   
    # for social media authentication
    path('accounts/', include('allauth.urls')),   
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dportal/urls.py
from django.urls import path
from .views import DPortalAPIView,PatientDataAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "dportal"  

urlpatterns = [path('', DPortalAPIView.dportal, name="dportal"),
               path('add-data/', DPortalAPIView.add_data, name="add-data"),
               path('dportal/<str:slug>/', DPortalAPIView.read_data, name="read-data"),
               path('data-list/review-data/publish-data/<int:id>', DPortalAPIView.publish_data, name="publish-data"),
               path('data-list/review-data/<int:id>', DPortalAPIView.review_data, name="review-data"),
               path('data-list/view-data/<int:id>', DPortalAPIView.view_data, name="view-data"),
               path('data-list/delete-data/<int:id>', DPortalAPIView.delete_data, name="delete-data"),
               path('data-list/', DPortalAPIView.data_list, name="data-list"),
               path('add-patient-data/', PatientDataAPIView.add_patient_data, name="add-patient-data"),
               path('patient-data-list/', PatientDataAPIView.patient_data_list, name="patient-data-list"),
               path('api/dportal/', DPortalAPIView.as_view(), name="dportal-api"),
               path("<slug:slug>", DPortalAPIView.as_view(), name="data_detail")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import HomeAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "home"  

urlpatterns = [
                path('', HomeAPIView.home, name = 'home'),
                path('api/home/', HomeAPIView.as_view(), name="home-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/urls.py
from django.urls import path
from .views import LabAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "lab"  

urlpatterns = [
                path('', LabAPIView.lab, name = 'lab'),
                path('lab/api/', LabAPIView.as_view(), name="lab-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.urls import path
from .views import ProjectAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "project"  
urlpatterns = [path('', ProjectAPIView.project, name="project"),
               path('add-project/', ProjectAPIView.add_project, name="add-project"),
               path('add-project/', ProjectAPIView.add_project, name="add-project"),
               # path('<str:slug>/', ProjectAPIView.read_project, name="index-read-project"),
               path('project/<str:slug>/', ProjectAPIView.read_project, name="read-project"),
               path('project-list/review-project/publish-project/<int:id>', ProjectAPIView.publish_project, name="publish-project"),
               path('project-list/review-project/<int:id>', ProjectAPIView.review_project, name="review-project"),
               path('project-list/view-project/<int:id>', ProjectAPIView.view_project, name="view-project"),
               path('project-list/delete-project/<int:id>', ProjectAPIView.delete_project, name="delete-project"),
               path('project-list/', ProjectAPIView.project_list, name="project-list"),
               path('api/project/', ProjectAPIView.as_view(), name="project-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

publication/urls.py
from django.urls import path
from .views import PublicationAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "publication"  

urlpatterns = [path('', PublicationAPIView.publication, name="publication"),
               path('add-publication/', PublicationAPIView.add_publication, name="add-publication"),
               path('add-publication/', PublicationAPIView.add_publication, name="add-publication"),
               # path('<str:slug>/', PublicationAPIView.read_publication, name="index-read-publication"),
               path('publication/<str:slug>/', PublicationAPIView.read_publication, name="read-publication"),
               path('publication-list/review-publication/publish-publication/<int:id>', PublicationAPIView.publish_publication, name="publish-publication"),
               path('publication-list/review-publication/<int:id>', PublicationAPIView.review_publication, name="review-publication"),
               path('publication-list/view-publication/<int:id>', PublicationAPIView.view_publication, name="view-publication"),
               path('publication-list/delete-publication/<int:id>', PublicationAPIView.delete_publication, name="delete-publication"),
               path('publication-list/', PublicationAPIView.publication_list, name="publication-list"),
               path('api/publication/', PublicationAPIView.as_view(), name="publication-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import UsersAPIView,MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"   

urlpatterns = [
    path('users/', UsersAPIView.as_view()),
    path('login_token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_request, name= "logout"),
    path("login/", views.login_request, name="login"),
    path("add_staff/", views.add_staff, name="add-staff"),
        path("staffs/", views.staffs, name="staffs"),
    path("register/", views.register_request, name="register"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workshop/urls.py
from django.urls import path
from .views import WorkshopAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "workshop"  

urlpatterns = [path('', WorkshopAPIView.workshop_22, name="workshop-22"),
               path('workshop/22/sessions', WorkshopAPIView.workshop_22_sessions, name="workshop-22-sessions"),
               path('workshop/22/speakers', WorkshopAPIView.workshop_22_sessions, name="workshop-22-speakers"),
               path('workshop/22/organizers', WorkshopAPIView.workshop_22_organizers, name="workshop-22-organizers"),
               path('api/workshop/', WorkshopAPIView.as_view(), name="workshop-api")
               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/forms.py
from django import forms
from django.utils import timezone
from .models import Project
from tinymce.widgets import TinyMCE
from ckeditor.fields import RichTextField
from ckeditor_uploader.widgets import CKEditorUploadingWidget

ta =(
    (0, "General"),
    (1, "Health Care"),
    (2, "Agriculture and Environmental Conversation"),
    (3, "Infrastructure and Data Ecosystem"),
    (4, "Digital Economy and Small Scale Industry"),
)
class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False
class ProjectForm(forms.ModelForm):
    thematic_area = forms.ChoiceField(choices=ta,widget=(forms.Select(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    title  = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    thumbnail = forms.ImageField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image'})))
    header_image = forms.ImageField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image'})))
    description = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id': 'description','placeholder': 'Description'})))
    # body  = forms.CharField(widget=TinyMCEWidget(attrs={'required': False, 'cols': 30, 'rows': 10, 'id':'body'}))
    # body = RichTextField()
    body = forms.CharField(widget=CKEditorUploadingWidget(attrs={'required': False, 'cols': 100, 'rows': 10, 'id':'body'}))
    
    class Meta:
        model = Project
        fields = ('thematic_area','title','thumbnail','description','body','header_image')

  
  


    

workshop/forms.py
from django import forms
from django.utils import timezone
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class WorkshopForm(forms.Form):
    workshop_name  = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Workshop Name'})))
    workshop_url  = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'website', 'placeholder':'Website URL'})))
    description  = forms.CharField(widget=CKEditorUploadingWidget(attrs={'required': False, 'cols': 100, 'rows': 10, 'id':'Description'}))
   


    

conference/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Conference
from .serializers import ConferenceModelSerializer
from django.contrib import messages
from .forms import ConferenceForm
# Create your views here.

class ConferenceAPIView(APIView):

    def get(self, request):
        conference = Conference.objects.all()
        serializer = ConferenceModelSerializer(conference, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = ConferenceModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def aaiac_23(request):
        return render(request, template_name='conference/aaiac2023/index.html', context={})
    
    def aaiac_23_contacts(request):
        return render(request, template_name='conference/aaiac2023/contacts.html', context={})

    def aaiac_23_organizers(request):
        return render(request, template_name='conference/aaiac2023/organizers.html', context={})
    
    def aaiac_23_call_for_paper(request):
        return render(request, template_name='conference/aaiac2023/call_for_paper.html', context={})

    def aaiac_23_speaker_malanga(request):
        return render(request, template_name='conference/aaiac2023/malanga.html', context={})

    def aaiac_23_speaker_andre(request):
        return render(request, template_name='conference/aaiac2023/andre.html', context={})

    def aaiac_23_speaker_chao(request):
        return render(request, template_name='conference/aaiac2023/chao.html', context={})

    def aaiac_23_speaker_denhere(request):
        return render(request, template_name='conference/aaiac2023/denhere.html', context={})

    def aaiac_23_speaker_deo(request):
        return render(request, template_name='conference/aaiac2023/deo.html', context={})
    
    def aaiac_23_speaker_dina(request):
        return render(request, template_name='conference/aaiac2023/dina.html', context={})

    def aaiac_23_speaker_essa(request):
        return render(request, template_name='conference/aaiac2023/essa.html', context={})

    def aaiac_23_speaker_gomez(request):
        return render(request, template_name='conference/aaiac2023/gomez.html', context={})

    def aaiac_23_speaker_juma(request):
        return render(request, template_name='conference/aaiac2023/juma.html', context={})

    def aaiac_23_speaker_jumanne(request):
        return render(request, template_name='conference/aaiac2023/jumanne.html', context={})

    def aaiac_23_speaker_kadeghe(request):
        return render(request, template_name='conference/aaiac2023/kadeghe.html', context={})
    
    def aaiac_23_speaker_lee(request):
        return render(request, template_name='conference/aaiac2023/leo.html', context={})

    def aaiac_23_speaker_linder(request):
        return render(request, template_name='conference/aaiac2023/linder.html', context={})

    def aaiac_23_speaker_mahadia(request):
        return render(request, template_name='conference/aaiac2023/mahadia.html', context={})

    def aaiac_23_speaker_mboni(request):
        return render(request, template_name='conference/aaiac2023/mboni.html', context={})

    def aaiac_23_speaker_mpho(request):
        return render(request, template_name='conference/aaiac2023/mpho.html', context={})

    def aaiac_23_speaker_msanjila(request):
        return render(request, template_name='conference/aaiac2023/msanjila.html', context={})

    def aaiac_23_speaker_mussa(request):
        return render(request, template_name='conference/aaiac2023/mussa.html', context={})

    def aaiac_23_speaker_sokhela(request):
        return render(request, template_name='conference/aaiac2023/sokhela.html', context={})
    
    def aaiac_23_speaker_thomas(request):
        return render(request, template_name='conference/aaiac2023/thomas.html', context={})

workshop/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Workshop
from .serializers import WorkshopModelSerializer
from django.contrib import messages
from .forms import WorkshopForm
# Create your views here.

class WorkshopAPIView(APIView):

    def get(self, request):
        workshop = Workshop.objects.all()
        serializer = WorkshopModelSerializer(workshop, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = WorkshopModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def workshop_22(request):
        return render(request, template_name='workshop/2022/index.html', context={})
    
    def workshop_22_organizers(request):
        return render(request, template_name='workshop/2022/organizers.html', context={})
    
    def workshop_22_sessions(request):
        return render(request, template_name='workshop/2022/sessions.html', context={})
    
    def workshop_22_speakers(request):
        return render(request, template_name='workshop/2022/speakers.html', context={})

templates/research/add_project.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <!-- <h3>Add Project</h3> -->
                <!-- <p class="text-subtitle text-muted">Textarea with rich features </p> -->
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'project:project-list' %}">View Projects</a></li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>

    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Add Project </h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'project:add-project' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name-column">Project Title</label>
                                            {{ project_form.title }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thumbnail</label>
                                            {{ project_form.thumbnail }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Header Image</label>
                                            {{ project_form.header_image }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thematic Area</label>
                                            {{ project_form.thematic_area }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Description</label>
                                            {{ project_form.description }}
                                        </div>
                                    </div>

                                    <div class="col-md-12 col-12">
                                        <label for="city-column">BODY</label>
                                        <div class="form-group">
                                            {{project_form.media}}
                                            {{ project_form.body | safe }}
                                        </div>
                                    </div>
                                    <div class="form-group col-12">

                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Add</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Basic multiple Column Form section end -->

</div>
{% endblock %}

templates/research/add_publication.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <!-- <h3>Add Project</h3> -->
                <!-- <p class="text-subtitle text-muted">Textarea with rich features </p> -->
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'publication:publication-list' %}">View Publications</a></li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>

    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Add Publication </h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'publication:add-publication' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name-column">Publication Title</label>
                                            {{ publication_form.title }}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thematic Area</label>
                                            {{ publication_form.thematic_area }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="country-floating">Publication Header Image</label>
                                            {{ publication_form.header_image }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Publication Document</label>
                                            {{ publication_form.file }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Description</label>
                                            {{ publication_form.description }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <label for="city-column">Abstract</label>
                                        <div class="form-group">
                                            {{ publication_form.media }}
                                            {{ publication_form.body | safe }}
                                        </div>
                                    </div>
                                    <div class="form-group col-12">

                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Add</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Basic multiple Column Form section end -->

</div>
{% endblock %}