ai4dlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views 
from users import urls as user_urls
from team import urls as team_urls
from home import urls as home_urls
from news import urls as news_urls
from blog import urls as blog_urls
from call import urls as call_urls
from colab import urls as colab_urls
from conference import urls as conference_urls
from dportal import urls as dportal_urls
from jupyinter import urls as jupyinter_urls
from partner import urls as partner_urls
from project import urls as project_urls
from publication import urls as publication_urls
from lab import urls as lab_urls
from workshop import urls as workshop_urls
from contact import urls as contact_urls
from sponsor import urls as sponsor_urls
from community import urls as community_urls
from learning import urls as learning_urls
from package import urls as package_urls
from users.forms import ConfirmResetForm
urlpatterns = [
    path('admin/', admin.site.urls),
    # include django browserable 
    path("auth-api/", include("rest_framework.urls", namespace="rest_framework")),
    # include django authentication 
    # path('accounts/', include('django.contrib.auth.urls'))
    path('', include(home_urls)),
    path('users/', include(user_urls)),
    path('team/', include(team_urls)),
    path('news/', include(news_urls)),
    path('blog/', include(blog_urls)),
    path('call/', include(call_urls)),
    path('colab/', include(colab_urls)),
    path('conference/', include(conference_urls)),
    path('workshop/', include(workshop_urls)),
    path('dportal/', include(dportal_urls)),
    path('jupyinter/', include(jupyinter_urls)),
    path('partner/', include(partner_urls)),
    path('project/', include(project_urls)),
    path('publication/', include(publication_urls)),
    path('lab/', include(lab_urls)),
    path('contact/', include(contact_urls)),
    path('sponsor/', include(sponsor_urls)),
    path('community/', include(community_urls)),
    path('learning/', include(learning_urls)),
    path('package/', include(package_urls)),
    # we can mention them this way
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=ConfirmResetForm, template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),   
    # for social media authentication
    path('accounts/', include('allauth.urls')),   
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import BlogAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"  

urlpatterns = [path('', BlogAPIView.blog, name="blog"),
               path('add-blog/', BlogAPIView.add_blog, name="add-blog"),
               path('blog/<str:slug>/', BlogAPIView.read_blog, name="read-blog"),
               path('blog-list/review-blog/publish-blog/<int:id>', BlogAPIView.publish_blog, name="publish-blog"),
               path('blog-list/review-blog/<int:id>', BlogAPIView.review_blog, name="review-blog"),
               path('blog-list/view-blog/<int:id>', BlogAPIView.view_blog, name="view-blog"),
               path('blog-list/delete-blog/<int:id>', BlogAPIView.delete_blog, name="delete-blog"),
               path('blog-list/', BlogAPIView.blog_list, name="blog-list"),
               path('api/blog/', BlogAPIView.as_view(), name="blog-api"),
               path("<slug:slug>", BlogAPIView.as_view(), name="blog_detail")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dportal/urls.py
from django.urls import path
from .views import DPortalAPIView,PatientDataAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "dportal"  

urlpatterns = [path('', DPortalAPIView.dportal, name="dportal"),
               path('add-data/', DPortalAPIView.add_data, name="add-data"),
               path('dportal/<str:slug>/', DPortalAPIView.read_data, name="read-data"),
               path('data-list/review-data/publish-data/<int:id>', DPortalAPIView.publish_data, name="publish-data"),
               path('data-list/review-data/<int:id>', DPortalAPIView.review_data, name="review-data"),
               path('data-list/view-data/<int:id>', DPortalAPIView.view_data, name="view-data"),
               path('data-list/delete-data/<int:id>', DPortalAPIView.delete_data, name="delete-data"),
               path('data-list/', DPortalAPIView.data_list, name="data-list"),
               path('add-patient-data/', PatientDataAPIView.add_patient_data, name="add-patient-data"),
               path('patient-data-list/', PatientDataAPIView.patient_data_list, name="patient-data-list"),
               path('api/dportal/', DPortalAPIView.as_view(), name="dportal-api"),
               path("<slug:slug>", DPortalAPIView.as_view(), name="data_detail")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import HomeAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "home"  

urlpatterns = [
                path('', HomeAPIView.home, name = 'home'),
                path('api/home/', HomeAPIView.as_view(), name="home-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jupyinter/urls.py
from django.urls import path
from .views import JupyinterAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "jupyinter"  

urlpatterns = [path('', JupyinterAPIView.jupyinter, name="jupyinter"),
              path('jupyinter', JupyinterAPIView.as_view(), name="jupyinter-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/urls.py
from django.urls import path
from .views import LabAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "lab"  

urlpatterns = [
                path('', LabAPIView.lab, name = 'lab'),
                path('lab/api/', LabAPIView.as_view(), name="lab-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import UsersAPIView,MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"   

urlpatterns = [
    path('users/', UsersAPIView.as_view()),
    path('login_token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_request, name= "logout"),
    path("login/", views.login_request, name="login"),
    path("add_staff/", views.add_staff, name="add-staff"),
        path("staffs/", views.staffs, name="staffs"),
    path("register/", views.register_request, name="register"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jupyinter/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.relpath(__file__)))

class Jupyinter(models.Model):
    id = models.AutoField(primary_key=True)
    status = models.IntegerField(max_length = 10, default=0)
    active = models.IntegerField(default=0)
    uploads = models.ImageField(max_length=200, blank=True,upload_to=os.path.join(BASE_DIR,'media/jupyinter'))
    slug = models.SlugField(null=False, unique=True)
    status = models.IntegerField(default=0)
    opened_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

        

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("jupyinter_detail", kwargs={"slug": self.slug}) 

jupyinter/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Jupyinter
from .serializers import JupyinterModelSerializer
# Create your views here.

class JupyinterAPIView(APIView):

    def get(self, request):
        team = Jupyinter.objects.all()
        serializer = JupyinterModelSerializer(team, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = JupyinterModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)


    def jupyinter(request):

        return render(request, template_name='tools/jupyinter.html', context={})

templates/tools/add_data.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <!-- <h3>Add Project</h3> -->
                <!-- <p class="text-subtitle text-muted">Textarea with rich features </p> -->
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'blog:blog-list' %}">View Data</a></li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>

    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Add Data </h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'dportal:add-data' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name-column">Data Name</label>
                                            {{ data_form.name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thematic Area</label>
                                            {{ data_form.thematic_area }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Data File</label>
                                            {{ data_form.file }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Description</label>
                                            {{ data_form.description }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <label for="city-column">BODY</label>
                                        <div class="form-group">
                                            {{ data_form.media }}
                                            {{ data_form.body | safe }}
                                        </div>
                                    </div>

                                    <div class="form-group col-12">

                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Add</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Basic multiple Column Form section end -->

</div>
{% endblock %}

templates/tools/data-portal.html
{% extends "../includes/master.html" %}
{% load static %}
{% block title %}AI4D Lab - About{% endblock %}
{% block content %}
    <!-- Start inner Page hero-->
    <section class="d-flex align-items-center page-hero  inner-page-hero " id="page-hero">
      <div class="overlay-photo-image-bg parallax" data-bg-img="{% static 'assets/images/hero/inner-page-hero.jpg' %}" data-bg-opacity="1"></div>
      <div class="overlay-color" data-bg-opacity=".75"></div>
      <div class="container">
        <div class="hero-text-area centerd">
          <h1 class="hero-title  wow fadeInUp" data-wow-delay=".2s">Data Portal</h1>
          <nav aria-label="breadcrumb ">
            <ul class="breadcrumb wow fadeInUp" data-wow-delay=".6s">
              <li class="breadcrumb-item"><a class="breadcrumb-link" href="{% url 'home:home' %}"><i class="bi bi-house icon "></i>home</a></li>
              <li class="breadcrumb-item active">data</li>
            </ul>
          </nav>
        </div>
      </div>
    </section>
    <!-- End inner Page hero-->
    <!-- Start blog-1-col-posts-->
    <section class="blog blog-home mega-section">
      <div class="container ">
        <div class="row ">
          <div class="col-12 col-xl-8 "> 
            <div class="posts-grid horizontal">
              <div class="row">
                {% if not data %}
                <div class="col-12">
                  <p>No data available.</p>
                </div>
                {% endif %}
                {% for d in data %}
                <div class="col-12 "> 
                  <div class="post-box">     <a class="post-link" href="#" title="helping others can boost you happiness"> 
                      {% comment %} <div class="post-img-wrapper  "><img class=" parallax-img   post-img" loading="lazy" src="{% static 'assets/images/blog/post-images/6.jpg' %}" alt=""/><span class="post-date"><span class="day">21 </span>jul 2022     </span></div></a> {% endcomment %}
                    <div class="post-summary">
                      {% if user.is_authenticated %}
                      <div class="post-info"><a class="info post-author" href="{{ d.file.url }}"> <i class=" bi bi-download icon"></i>Download</a></div>
                      {% endif %}
                      {% if not user.is_authenticated %}
                      <div class="post-info"><a class="info post-author" href="{% url 'users:login' %}"> <i class=" bi bi-download icon"></i>Download</a></div>
                      {% endif %}
                      <div class="post-text"><a class="post-link" href="dportal/{{ d.slug }}"> 
                          <h2 class="post-title"> {{ d.name }}</h2></a>
                        <p class="post-excerpt">{{ d.description }}</p><a class="read-more" href="dportal/{{d.slug}}" title="helping others can boost you happiness">View Details<i class="bi bi-arrow-right icon "></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
                <div class="col-12">
                  <!--Start pagination-->
                  {% comment %} <nav class="ma-pagination">
                    <ul class="pagination justify-content-center">
                      <li class="ma-page-item deactive-page-item"><a class="ma-page-link " href="#" title="Previous Page"><i class="bi bi-chevron-left icon "></i></a></li>
                      <li class="ma-page-item active"><a class="ma-page-link " href="#">1 </a></li>
                      <li class="ma-page-item  "><a class="ma-page-link " href="#">2 </a></li>
                      <li class="ma-page-item  "><a class="ma-page-link " href="#">3 </a></li>
                      <li class="ma-page-item"><a class="ma-page-link" href="#" title="Next Page"><i class="bi bi-chevron-right icon "></i></a></li>
                    </ul>
                  </nav> {% endcomment %}
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-xl-4 ">
            <div class="blog-sidebar">
              <!--search box-->
              <div class="search sidebar-box">
                <form class="search-form" action="#">
                  <input class="search-input" type="search" name="seach_form" placeholder="Search Data...">
                  <button class="search-btn" type="submit"><i class="bi bi-search icon"></i></button>
                </form>
              </div>
              <!--categories box-->
              <div class="cats sidebar-box">
                <h6 class="sidebar-box-title">
                   Categories:</h6>
                <ul class="sidebar-list cats-list  ">
                  <li class="cat-item"><a class="cat-link" href="#">General<span class="cat-count">{{ general_count}}</span></a></li>
                  <li class="cat-item"><a class="cat-link" href="#">Health Care<span class="cat-count">{{ health_count}}</span></a></li>
                  <li class="cat-item"><a class="cat-link" href="#">Agriculture and Environmental Conversation<span class="cat-count">{{ agriculture_count }}</span></a></li>
                  <li class="cat-item"><a class="cat-link" href="#">Infrastructure and Data Ecosystem<span class="cat-count">{{ infra_count }}</span></a></li>
                  <li class="cat-item"><a class="cat-link" href="#">Digital Economy and Small Scale Industry<span class="cat-count">{{ digital_count }}</span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End blog-1-col-posts-->
   {% endblock %}

templates/tools/data_list.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Data</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'dportal:add-data' %}">Add Data</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                
            </div>
            <div class="card-body">
                <table class='table table-responsive table-hover table-striped' id="table1">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Uploaded By</th>
                            <th>Name</th>
                            {% comment %} <th>Slug</th> {% endcomment %}
                            <!-- <th>Affiliation</th> -->
                            <!-- <th>Email</th> -->
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for d in data %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ d.publisher }}</td>
                            <td>{{ d.name }}</td>
                            {% comment %} <td>{{ blog.slug }}</td> {% endcomment %}
                            <td>
                                {% if d.publish == 1%}
                                <span class="badge bg-success">Published</span>
                                {% endif %}
                                {% if d.publish == 0 %}
                                <span class="badge bg-danger">Not published</span>
                                {% endif %}
                            </td>
                            <td>
                                <a class="btn btn-success btn-xs" href="">Edit</a>
                                {% if d.publish == 1 %}
                                <a class="btn btn-primary btn-xs" href="view-data/{{d.id}}">View</a>
                                <a class="btn btn-danger btn-xs" href="delete-data/{{d.id}}">Delete</a>
                                {% endif %}
                                {% if d.publish == 0 %}
                                <a class="btn btn-primary btn-xs" href="review-data/{{d.id}}">Review</a>
                                {%  endif%}
                            </td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>

    </section>
</div>
        </div>
    </div>
</body>
{% endblock %}

templates/tools/patient_data_list.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Patient Data</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'dportal:add-patient-data' %}">Add Patient Data</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                
            </div>
            <div class="card-body">
                <table class='table table-responsive table-hover table-striped' id="table1">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Patient ID</th>
                            <th>Age</th>
                            <th>Country</th> 
                            <th>District</th>
                            <th>Region</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for patient in data %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ patient.patient_id }}</td>
                            <td>{{ patient.age }}</td>
                            <td>{{ patient.country }}</td>
                            <td>{{ patient.district }}</td>
                            <td>{{ patient.region }}</td>
                            {% comment %} <td>
                                <a class="btn btn-success btn-xs" href="">Edit</a>
                                <a class="btn btn-primary btn-xs" href="view-patient-data/{{ patient.id }}">View</a>
                                <a class="btn btn-danger btn-xs" href="delete-patient-data/{{ patient.id }}">Delete</a>
                            </td> {% endcomment %}
                            <td>
                            <a class="btn btn-success btn-xs" href="#">Edit</a>
                            <a class="btn btn-primary btn-xs" href="#">View</a>
                            <a class="btn btn-danger btn-xs" href="#">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                    
            </div>
        </div>

    </section>
</div>
        </div>
    </div>
</body>
{% endblock %}