blog/urls.py
from django.urls import path
from .views import BlogAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"  

urlpatterns = [path('', BlogAPIView.blog, name="blog"),
               path('add-blog/', BlogAPIView.add_blog, name="add-blog"),
               path('blog/<str:slug>/', BlogAPIView.read_blog, name="read-blog"),
               path('blog-list/review-blog/publish-blog/<int:id>', BlogAPIView.publish_blog, name="publish-blog"),
               path('blog-list/review-blog/<int:id>', BlogAPIView.review_blog, name="review-blog"),
               path('blog-list/view-blog/<int:id>', BlogAPIView.view_blog, name="view-blog"),
               path('blog-list/delete-blog/<int:id>', BlogAPIView.delete_blog, name="delete-blog"),
               path('blog-list/', BlogAPIView.blog_list, name="blog-list"),
               path('api/blog/', BlogAPIView.as_view(), name="blog-api"),
               path("<slug:slug>", BlogAPIView.as_view(), name="blog_detail")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

call/urls.py
from django.urls import path
from .views import CallAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "call"  

urlpatterns = [path('', CallAPIView.call, name="call"),
               path('add-call/', CallAPIView.add_call, name="add-call"),
               path('call/<str:slug>/', CallAPIView.read_call, name="read-call"),
               path('call-list/review-call/publish-call/<int:id>', CallAPIView.publish_call, name="publish-call"),
               path('call-list/review-call/<int:id>', CallAPIView.review_call, name="review-call"),
               path('call-list/view-call/<int:id>', CallAPIView.view_call, name="view-call"),
               path('call-list/delete-call/<int:id>', CallAPIView.delete_call, name="delete-call"),
               path('call-list/', CallAPIView.call_list, name="call-list"),
               path('api/call/', CallAPIView.as_view(), name="call-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import HomeAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "home"  

urlpatterns = [
                path('', HomeAPIView.home, name = 'home'),
                path('api/home/', HomeAPIView.as_view(), name="home-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab/urls.py
from django.urls import path
from .views import LabAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "lab"  

urlpatterns = [
                path('', LabAPIView.lab, name = 'lab'),
                path('lab/api/', LabAPIView.as_view(), name="lab-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path,re_path
from .views import NewsAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "news"  

urlpatterns = [path('', NewsAPIView.news, name="news"),
               path('add-news/', NewsAPIView.add_news, name="add-news"),
               # path('<str:slug>/', NewsAPIView.read_news, name="index-read-news"),
               path('news/<str:slug>/', NewsAPIView.read_news, name="read-news"),
               path('news-list/review-news/publish-news/<int:id>', NewsAPIView.publish_news, name="publish-news"),
               path('news-list/review-news/<int:id>', NewsAPIView.review_news, name="review-news"),
               path('news-list/view-news/<int:id>', NewsAPIView.view_news, name="view-news"),
               path('news-list/delete-news/<int:id>', NewsAPIView.delete_news, name="delete-news"),
               path('news-list/', NewsAPIView.news_list, name="news-list"),
               path('api/news', NewsAPIView.as_view(), name="news-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if not settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from .views import UsersAPIView,MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"   

urlpatterns = [
    path('users/', UsersAPIView.as_view()),
    path('login_token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_request, name= "logout"),
    path("login/", views.login_request, name="login"),
    path("add_staff/", views.add_staff, name="add-staff"),
        path("staffs/", views.staffs, name="staffs"),
    path("register/", views.register_request, name="register"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/forms.py
from django import forms
from django.utils import timezone
from .models import Blog
from ckeditor_uploader.widgets import CKEditorUploadingWidget

ta =(
    (0, "General"),
    (1, "Health Care"),
    (2, "Agriculture and Environmental Conversation"),
    (3, "Infrastructure and Data Ecosystem"),
    (4, "Digital Economy and Small Scale Industry"),
)

class BlogForm(forms.ModelForm):
    title  = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    thematic_area = forms.ChoiceField(choices=ta, widget=(forms.Select(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    thumbnail = forms.ImageField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image'})))
    description  = forms.CharField(max_length=5000, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'bio', 'placeholder':'Description'})))
    body = forms.CharField(widget=CKEditorUploadingWidget(attrs={'required': False, 'cols': 100, 'rows': 10, 'id':'body'}))
    header_image = forms.ImageField(required=False, max_length=200, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image','required':'false'})))
    file = forms.FileField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose File'})))
    # author  = forms.CharField(max_length=100, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'publisher-name', 'placeholder':'Full Name'})))
    
    class Meta:
        model = Blog
        fields = ['header_image']


    

call/forms.py
from django import forms
from django.utils import timezone
from .models import Call
from ckeditor_uploader.widgets import CKEditorUploadingWidget

ta =(
    (0, "General"),
    (1, "Health Care"),
    (2, "Agriculture and Environmental Conversation"),
    (3, "Infrastructure and Data Ecosystem"),
    (4, "Digital Economy and Small Scale Industry"),
)

class CallForm(forms.ModelForm):
    title  = forms.CharField(max_length=500, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    thematic_area = forms.ChoiceField(choices=ta, widget=(forms.Select(attrs={'class': 'form-control', 'id':'partner-name', 'placeholder':'Title'})))
    file = forms.FileField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose File'})))
    thumbnail = forms.ImageField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image'})))
    header_image = forms.ImageField(max_length=500, widget=(forms.FileInput(attrs={'class': 'form-control ','id': 'photo','placeholder': 'Choose image'})))
    description  = forms.CharField(max_length=5000, widget=(forms.TextInput(attrs={'class': 'form-control', 'id':'bio', 'placeholder':'Description'})))
    body = forms.CharField(widget=CKEditorUploadingWidget(attrs={'required': False, 'cols': 100, 'rows': 10, 'id':'body'}))
    
    class Meta:
        model = Call
        fields = ['file']


    

blog/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Blog
from .forms import BlogForm
from .serializers import BlogModelSerializer
from django.contrib import  messages
from django.contrib.auth.models import User
# Create your views here.

class BlogAPIView(APIView):

    def get(self, request):
        blogs = Blog.objects.all()
        serializer = BlogModelSerializer(blogs, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = BlogModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def blog_list(request):
        blogs = Blog.objects.all()
        context = {'blogs':blogs}
        return render(request, template_name='updates/blogs_list.html', context=context)

    def blog(request):
        blogs = Blog.objects.filter(publish=1, status=1)
        general_count = len(Blog.objects.filter(thematic_area=0))
        health_count = len(Blog.objects.filter(thematic_area=1))
        agriculture_count = len(Blog.objects.filter(thematic_area=2))
        infra_count = len(Blog.objects.filter(thematic_area=3))
        digital_count = len(Blog.objects.filter(thematic_area=4))
        context = {"blogs": blogs,'general_count':general_count,'health_count':health_count,
                   'agriculture_count':agriculture_count, 'infra_count':infra_count,'digital_count':digital_count}
        return render(request, template_name='updates/blog.html', context=context)

    def add_blog(request):

        if request.method == 'POST' and request.FILES['thumbnail']:

            call_form = BlogForm(request.POST,request.FILES)

            if call_form.is_valid():
                title  = request.POST['title']
                description = request.POST['description']
                body = request.POST['body']
                file= request.FILES['file']
                thumbnail = request.FILES['thumbnail']
                header_image = request.FILES['header_image']
                thematic_area= request.POST['thematic_area']
                status = 1
                slug = title.replace(' ','-').lower()
                new_blog = Blog(title=title, description=description, body=body, thumbnail=thumbnail,thematic_area=thematic_area, header_image=header_image,file=file, status=status,author_id=request.session['user_id'], slug=slug)
                get_objects = Blog.objects.filter(title=title, status=1)
                if get_objects:
                    messages.success(request, "Blog already exist." )
                    blog_form = BlogForm()
                    return render(request, template_name='updates/add_blog.html', context={'blog_form':blog_form})
                else:
                    new_blog.save()
                    messages.success(request, "Blog successful added." )
                    return redirect('blog:blog-list')
            else:
                print(blog_form.errors.as_data())
                
        blog_form = BlogForm()
        return render(request, template_name='updates/add_blog.html', context={'blog_form':blog_form})


    def review_blog(request,id):
        blog = Blog.objects.get(id=id)
        context = {'blog':blog}
        return render(request, template_name='updates/review_blog.html', context=context)
    
    def read_blog(request,slug):
        blog = Blog.objects.get(slug=slug)
        author = User.objects.get(id=blog.author_id)
        author_posts = Blog.objects.filter(author_id=blog.author_id).exclude(slug=slug)
        author_next = author_prev = None
        if len(author_posts) > 1:
            author_next = author_posts[0]
            author_prev = author_posts[1]
        context = {'blog':blog, 'author':author, 'author_posts':author_posts,'author_next':author_next, 'author_prev':author_prev}
        return render(request, template_name='updates/blog_single.html', context=context)
    
    def view_blog(request,id):
        blog = Blog.objects.get(id=id)
        context = {'blog':blog}
        return render(request, template_name='updates/view_blog.html', context=context)
    
    def publish_blog(request,id):
            blog = Blog.objects.get(id=id)
            blog.publish = 1
            blog.save()
            return redirect('blog:blog-list')
            
    
    def delete_blog(request,id):
        blog = Blog.objects.filter(id=id)
        if blog:
            blog.delete()
            messages.success(request, "Blog deleted." )
            return redirect('blog:blog-list')
        messages.success(request, "Blog doesn't exist." )
        return redirect('blog:blog-list')

call/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Call
from .serializers import CallModelSerializer
from django.contrib import messages
from .forms import CallForm
from django.contrib.auth.models import User
# Create your views here.

class CallAPIView(APIView):

    def get(self, request):
        calls = Call.objects.all()
        serializer = CallModelSerializer(calls, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = CallModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)

    def call_list(request):
        calls = Call.objects.all()
        context = {'calls':calls}
        return render(request, template_name='updates/call_list.html', context=context)

    def call(request):
        calls = Call.objects.filter(publish=1, status=1)
        context = {"calls": calls}
        return render(request, template_name='updates/call.html', context=context)

    def add_call(request):

        if request.method == 'POST' and request.FILES['thumbnail']:

            call_form = CallForm(request.POST,request.FILES)

            if call_form.is_valid():
                title  = request.POST['title']
                description = request.POST['description']
                body = request.POST['body']
                thumbnail = request.FILES['thumbnail']
                header_image = request.FILES['header_image']
                file= request.FILES['file']
                thematic_area= request.POST['thematic_area']
                status = 1
                slug = title.replace(' ','-').lower()
                new_call = Call(title=title, description=description, body=body, thumbnail=thumbnail,file=file,thematic_area=thematic_area, header_image=header_image, status=status,publisher_id=request.session['user_id'], slug=slug)
                get_objects = Call.objects.filter(title=title, status=1)
                if get_objects:
                    messages.success(request, "call already exist." )
                    call_form = CallForm()
                    return render(request, template_name='updates/add_call.html', context={'call_form':call_form})
                else:
                    new_call.save()
                    messages.success(request, "call successful added." )
                    return redirect('call:call-list')
            else:
                print(call_form.errors.as_data())
                
        call_form = CallForm()
        return render(request, template_name='updates/add_call.html', context={'call_form':call_form})


    def review_call(request,id):
        call = Call.objects.get(id=id)
        context = {'call':call}
        return render(request, template_name='updates/review_call.html', context=context)
    
    def read_call(request,slug):
        call = Call.objects.get(slug=slug)
        publisher = User.objects.get(id=call.publisher_id)
        publisher_posts = Call.objects.filter(publisher_id=call.publisher_id).exclude(slug=slug)
        context = {'call':call, 'publisher_posts':publisher_posts,'publisher':publisher, 'publisher_posts':publisher_posts[:3]}
        return render(request, template_name='updates/call_single.html', context=context)
    
    def view_call(request,id):
        call = call.objects.get(id=id)
        context = {'call':call}
        return render(request, template_name='updates/view_call.html', context=context)
    
    def publish_call(request,id):
            call = Call.objects.get(id=id)
            call.publish = 1
            call.save()
            return redirect('call:call-list')
            
    
    def delete_call(request,id):
        call = Call.objects.filter(id=id)
        if call:
            call.delete()
            messages.success(request, "call deleted." )
            return redirect('call:call-list')
        messages.success(request, "call doesn't exist." )
        return redirect('call:call-list')

templates/updates/add_news.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <!-- <h3>Add Project</h3> -->
                <!-- <p class="text-subtitle text-muted">Textarea with rich features </p> -->
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'news:news-list' %}">View News</a></li>
                    </ol>
                </nav>
            </div>
        </div>

    </div>

    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Add News </h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'news:add-news' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="first-name-column">News Title</label>
                                            {{ news_form.title }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thumbnail</label>
                                            {{ news_form.thumbnail }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Header Image</label>
                                            {{ news_form.header_image }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Thematic Area</label>
                                            {{ news_form.thematic_area }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Description</label>
                                            {{ news_form.description }}
                                        </div>
                                    </div>

                                    <div class="col-md-12 col-12">
                                        <label for="city-column">BODY</label>
                                        <div class="form-group">
                                            {{news_form.media}}
                                            {{ news_form.body | safe }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="city-column">Attachment</label>
                                            {{ news_form.file }}
                                        </div>
                                    </div>
                                    <div class="form-group col-12">

                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Add</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Basic multiple Column Form section end -->

</div>
{% endblock %}

templates/updates/blog_list.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
               / <h3>Blogs</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'blog:add-blog' %}">Add Blog</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                <!-- Simple Datatable -->
            </div>
            <div class="card-body">
                <table class='table table-responsive table-hover table-striped' id="table1">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>City</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Kermit</td>
                            <td>diam.Sed.diam@anteVivamusnon.org</td>
                            <td>(01653) 27844</td>
                            <td>Patna</td>
                            <td>
                                <span class="badge bg-success">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Jermaine</td>
                            <td>sodales@nuncsit.org</td>
                            <td>0800 528324</td>
                            <td>Mold</td>
                            <td>
                                <span class="badge bg-success">Active</span>
                            </td>
                        </tr>
                        <tr>
                            <td>Ferdinand</td>
                            <td>gravida.molestie@tinciduntadipiscing.org</td>
                            <td>(016977) 4107</td>
                            <td>Marlborough</td>
                            <td>
                                <span class="badge bg-danger">Inactive</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </section>
</div>
        </div>
    </div>
</body>
{% endblock %}

templates/updates/news.html
{% extends "../includes/master.html" %}
{% load static %}
{% block title %}AI4D Lab - About{% endblock %}
{% block content %}
    <!-- Start inner Page hero-->
    <section class="d-flex align-items-center page-hero  inner-page-hero " id="page-hero">
      <div class="overlay-photo-image-bg parallax" data-bg-img="{% static 'assets/images/hero/inner-page-hero.jpg' %}" data-bg-opacity="1"></div>
      <div class="overlay-color" data-bg-opacity=".75"></div>
      <div class="container">
        <div class="hero-text-area centerd">
          <h1 class="hero-title  wow fadeInUp" data-wow-delay=".2s">News</h1>
          <nav aria-label="breadcrumb ">
            <ul class="breadcrumb wow fadeInUp" data-wow-delay=".6s">
              <li class="breadcrumb-item"><a class="breadcrumb-link" href="{% url 'home:home' %}"><i class="bi bi-house icon "></i>home</a></li>
              <li class="breadcrumb-item active">news</li>
            </ul>
          </nav>
        </div>
      </div>
    </section>
    <!-- End inner Page hero-->
    <!-- Start  portfolio Section-->
    <section class="portfolio portfolio-slider    mega-section" id="portfolio">
      <div class="container">
        <div class="sec-heading  ">
          {% comment %} <div class="content-area"><span class=" pre-title       wow fadeInUp " data-wow-delay=".2s">portfolio</span>
            <h2 class=" title    wow fadeInUp" data-wow-delay=".4s">Awesome <span class='hollow-text'>portfolio</span></h2>
          </div> {% endcomment %}
          {% comment %} <div class=" cta-area   wow fadeInUp" data-wow-delay=".8s"><a class="cta-btn btn-solid    " href="portfolio-slider.html">see more <i class="bi bi-arrow-right icon "></i></a></div> {% endcomment %}
        </div>
        <!--Swiper-->
        <div class="swiper-container wow fadeIn" data-wow-delay=".5s">
          <div class="swiper-wrapper ">
            {% for new in news %}
            <div class="swiper-slide">
              <div class="item   "><a class="portfolio-img-link" href="news/{{ new.slug}}"><img class="portfolio-img   img-fluid " loading="lazy" src="{{ new.thumbnail.url }}" alt="{{ new.title }}"/></a>
                <div class="item-info ">
                  <h3 class="item-title">{{ new.title }}</h3><i class="bi bi-arrow-right icon "></i>
                </div>
              </div>
            </div>
            {% endfor %}
            </div>
          </div>
          <!--navigation buttons-->
          <div class="swiper-button-prev">
            <div class="left-arrow"><i class="bi bi-chevron-left icon "></i>
            </div>
          </div>
          <div class="swiper-button-next">
            <div class="right-arrow"><i class="bi bi-chevron-right icon "></i>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End  portfolio Section-->
  {% endblock %}