ai4dlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views 
from users import urls as user_urls
from team import urls as team_urls
from home import urls as home_urls
from news import urls as news_urls
from blog import urls as blog_urls
from call import urls as call_urls
from colab import urls as colab_urls
from conference import urls as conference_urls
from dportal import urls as dportal_urls
from jupyinter import urls as jupyinter_urls
from partner import urls as partner_urls
from project import urls as project_urls
from publication import urls as publication_urls
from lab import urls as lab_urls
from workshop import urls as workshop_urls
from contact import urls as contact_urls
from sponsor import urls as sponsor_urls
from community import urls as community_urls
from learning import urls as learning_urls
from package import urls as package_urls
from users.forms import ConfirmResetForm
urlpatterns = [
    path('admin/', admin.site.urls),
    # include django browserable 
    path("auth-api/", include("rest_framework.urls", namespace="rest_framework")),
    # include django authentication 
    # path('accounts/', include('django.contrib.auth.urls'))
    path('', include(home_urls)),
    path('users/', include(user_urls)),
    path('team/', include(team_urls)),
    path('news/', include(news_urls)),
    path('blog/', include(blog_urls)),
    path('call/', include(call_urls)),
    path('colab/', include(colab_urls)),
    path('conference/', include(conference_urls)),
    path('workshop/', include(workshop_urls)),
    path('dportal/', include(dportal_urls)),
    path('jupyinter/', include(jupyinter_urls)),
    path('partner/', include(partner_urls)),
    path('project/', include(project_urls)),
    path('publication/', include(publication_urls)),
    path('lab/', include(lab_urls)),
    path('contact/', include(contact_urls)),
    path('sponsor/', include(sponsor_urls)),
    path('community/', include(community_urls)),
    path('learning/', include(learning_urls)),
    path('package/', include(package_urls)),
    # we can mention them this way
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=ConfirmResetForm, template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),   
    # for social media authentication
    path('accounts/', include('allauth.urls')),   
    path('tinymce/', include('tinymce.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lab/urls.py
from django.urls import path
from .views import LabAPIView
from django.conf import settings
from django.conf.urls.static import static
app_name = "lab"  

urlpatterns = [
                path('', LabAPIView.lab, name = 'lab'),
                path('lab/api/', LabAPIView.as_view(), name="lab-api")] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import UsersAPIView,MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"   

urlpatterns = [
    path('users/', UsersAPIView.as_view()),
    path('login_token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_request, name= "logout"),
    path("login/", views.login_request, name="login"),
    path("add_staff/", views.add_staff, name="add-staff"),
        path("staffs/", views.staffs, name="staffs"),
    path("register/", views.register_request, name="register"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    # custom fields for userprofile
    first_name = models.CharField(max_length=500)
    last_name = models.CharField(max_length=500)
    email = models.EmailField(max_length=500, null=False, blank=False)
    status = models.IntegerField(default=0)
    role_choices = [
        ('pi', 'Principal Investigator'),
        ('co_pi', 'Co-Principal Investigator'),
        ('ltc', 'Lab Training Coordinator'),
        ('lo', 'Laison Officer'),
        ('coordinator', 'Coordinator'),
        ('asst_coordinator', 'Assistant Coordinator'),
        ('researcher', 'Researcher'),
        ('asst_researcher', 'Assistant Researcher'),
        ('innovator', 'Innovator'),
        ('student', 'Student'),
    ]
    role = models.CharField(max_length=20, choices=role_choices)
    password = models.CharField(max_length=500) 

    # Set unique related names for groups and user_permissions
UserProfile._meta.get_field("groups").remote_field.related_name = "userprofile_groups"
UserProfile._meta.get_field("user_permissions").remote_field.related_name = "userprofile_user_permissions"

users/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
# from rest_framework import viewsets
from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import UserModelSerializer, MyTokenObtainPairSerializer
from django.contrib.auth.models import User
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from rest_framework import viewsets
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm 
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django import template
from .forms import UserLoginForm, ResetPasswordForm
from .forms import StaffForm
from .models import UserProfile
from django.contrib.auth.hashers import check_password,make_password
class UsersAPIView(APIView):

    def get(self, request):
        users = User.objects.all()
        serializer = UserModelSerializer(users, many = True)
        return Response(serializer.data)
    
    def post(self, request):
        serializer = UserModelSerializer(data = request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status = 201)
        return Response(serializer.errors, status = 400)


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer


def register_request(request):
    if request.method == 'POST':
       register_form = NewUserForm(request.POST)
       if register_form.is_valid():
          user = register_form.save()
          username = register_form.cleaned_data.get('username')
          messages.success(request, "Registration successful." )
        #   login(request, user)
          login(request, user, backend='django.contrib.auth.backends.ModelBackend')
          return redirect("users:dashboard")
       else:
          messages.error(request,"Account creation failed")
          print(register_form.errors.as_data()) # here you print errors to terminal
          return redirect("users:register")

    register_form = NewUserForm()
    return render (request=request, template_name="users/register.html", context={"register_form":register_form})

def update_user(request,id):
		user= User.objects.get(id=id)
		update_form = NewUserForm(instance=user)# prepopulate the form with an existing band
		return render(request, 'users/update_user.html',{'update_form': update_form})


# def login_request(request):
#     print("Am in 1")
#     if request.method == "POST":
#         print("Am in 2")
#         try:
#             print("Am in 3")
#             form = UserLoginForm(request, data=request.POST)
#             print("Am in 4")
#             username = request.POST['username']
#             password = request.POST['password']
#             if form.is_valid():
#                 print("Am in 5")
#                 username = form.cleaned_data.get('username')
#                 password = form.cleaned_data.get('password')
#                 print("Form in", password)
#                 user = authenticate(username=username, password=password)
#                 print("Auth good")
#                 if user is not None:
#                     login(request, user)
#                     messages.info(request, f"You are now logged in as {username}.")
#                     request.session['user_id'] = user.id
#                     return redirect("users:dashboard")
#                 else:
#                     print("User not found")
#                     messages.error(request, "Invalid username or password.")
#             elif UserProfile.objects.filter(username=username).exists():
#                 print("From UserProfile")
#                 user = UserProfile.objects.get(username=username, password=password)
#                 login(request, user)
#                 messages.info(request, f"You are now logged in as {username}.")
#                 request.session['user_id'] = user.id
#                 return redirect("users:dashboard")
#             else:
#                 print(form.errors.as_data())
#                 messages.error(request, "Invalid username or password.")
#         except Exception as e:
#             print("Error: ", e)
#             messages.error(request, f"An error occurred: {str(e)}")

#     login_form = UserLoginForm()
#     return render(request=request, template_name="users/login.html", context={"login_form": login_form})

def login_request(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            try:
                user = authenticate(request, username=username, password=password)
                custom_user_data = UserProfile.objects.filter(username=username)
                if user and user.is_active:
                    login(request, user)
                    request.session['user_id'] = user.id
                    return redirect("users:dashboard")
                elif custom_user_data:
                    try:
                        custom_user = UserProfile.objects.get(username=username)
                        if check_password(password, custom_user.password):
                            print("Custom user password check successful")
                            backend = 'users.backends.CustomUserBackend'
                            login(request, custom_user, backend=backend)
                            request.session['user_id'] = custom_user.id
                            request.session['username'] = custom_user.username
                            request.session['role'] = custom_user.role
                            return redirect("users:dashboard")
                        else:
                            print("Password check failed")
                    except UserProfile.DoesNotExist:
                        print("User not found")
                    except Exception as e:
                        print(f"An unexpected error occurred: {e}")

                    else:
                        form.add_error(None, 'Invalid username or password.')
                else:
                    # Authentication failed, display an error message
                    form.add_error(None, 'Invalid username or password.')
                    

            except UserProfile.DoesNotExist:
                # Handle the case where the custom user does not exist
                form.add_error('username', 'User does not exist.')
            except Exception as e:
                # Handle other exceptions, log them, or take appropriate action
                print(f"An unexpected error occurred: {e}")
                form.add_error(None, 'An unexpected error occurred during authentication.')
        else:
            print(form.errors.as_data())
            messages.error(request, "Invalid username or password.")
    else:
        login_form = UserLoginForm()
        return render(request=request, template_name="users/login.html", context={"login_form": login_form})

def dashboard(request):
    return render(request, template_name = 'dashboards/admin.html', context={})

def logout_request(request):
	request.session.clear()  # Clears all session data for the current sessio
    # request.session.flush()  # Same as clear(), but also deletes the session cookie
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("home:home")

#email sms single alternative

# def password_reset_request(request):
# 	if request.method == "POST":
# 		password_reset_form = PasswordResetForm(request.POST)
# 		if password_reset_form.is_valid():
# 			data = password_reset_form.cleaned_data['email']
# 			associated_users = User.objects.filter(Q(email=data))
# 			if associated_users.exists():
# 				for user in associated_users:
# 					subject = "Password Reset Requested"
# 					email_template_name = "main/password/password_reset_email.txt"
# 					c = {
# 					"email":user.email,
# 					'domain':'127.0.0.1:8000',
# 					'site_name': 'Website',
# 					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
# 					'token': default_token_generator.make_token(user),
# 					'protocol': 'http',
# 					}
# 					email = render_to_string(email_template_name, c)
# 					try:
# 						send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
# 					except BadHeaderError:

# 						return HttpResponse('Invalid header found.')
						
# 					messages.success(request, 'A message with reset password instructions has been sent to your inbox.')
# 					return redirect ("main:homepage")
# 			messages.error(request, 'An invalid email has been entered.')
# 	password_reset_form = PasswordResetForm()
# 	return render(request=request, template_name="main/password/password_reset.html", context={"password_reset_form":password_reset_form})

# send email multi alternative
def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = ResetPasswordForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data)|Q(username=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					plaintext = template.loader.get_template('users/password/password_reset_email.txt')

templates/users/add_staff.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <!-- <h3>Add Member</h3> -->
                <!-- <p class="text-subtitle text-muted">There's a lot of form layout that you can use</p> -->
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'users:staffs' %}">View Staff Members</a></li>
                    </ol>
                </nav>
            </div>
        </div>

    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Add Lab Staff </h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <form class="form" method="POST" action="{% url 'users:add-staff' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name">First Name</label>
                                                {{ staff_form.first_name }} 
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name">Last Name</label>
                                                {{ staff_form.last_name }} 
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="first-name">Username</label>
                                                {{ staff_form.username }} 
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            {{ staff_form.email }}
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="first-name">Role</label>
                                                {{ staff_form.role }} 
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="phone">Password</label>
                                           {{ staff_form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="phone">Password</label>
                                           {{ staff_form.password2 }}
                                        </div>
                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1">Add</button>
                                        <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- // Basic multiple Column Form section end -->
</div>

        </div>
    </div>
</body>
</html>
{% endblock %}

templates/users/dashboard.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Testing Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome, {{user.username}}</a>
        </li>
  
        {% else %}
  
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
  
        {% endif %}
      </ul>
    </div>
  </nav>

templates/users/login.html
{% extends "includes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% block title %}AI4D Lab - Login{% endblock %}
{% block content %}
<body>
    <div id="auth">
<div class="container">
    <div class="row">
        <div class="col-md-5 col-sm-12 mx-auto">
            <div class="card pt-4">
                <div class="card-body">
                    <div class="text-center mb-5">
                        <img src="{% static 'dashboards/assets/images/logo.png' %}" height="100" class='mb-4'>
                        <h3>Sign In</h3>
                        <p>You're about to sign in to AI4D Lab.</p>
                    </div>
                    <form action="{% url 'users:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group position-relative has-icon-left">
                            <label for="username">Username</label>
                            <div class="position-relative">
                                {{ login_form.username  }}
                                <!-- <input type="text" class="form-control" id="username"> -->
                                <div class="form-control-icon">
                                    <i data-feather="user"></i>
                                </div>
                            </div>
                        </div>
                        <div class="form-group position-relative has-icon-left">
                            <div class="clearfix">
                                <label for="password">Password</label>
                                <a href="{% url 'users:password_reset' %}" class='float-right'>
                                    <small>Forgot password?</small>
                                </a>
                            </div>
                            <div class="position-relative">
                                <!-- <input type="text" class="form-control" id="password"> -->
                                {{ login_form.password }}
                                <div class="form-control-icon">
                                    <i data-feather="lock"></i>
                                </div>
                            </div>
                        </div>

                        <div class='form-check clearfix my-4'>
                            <div class="checkbox float-left">
                                <input type="checkbox" id="checkbox1" class='form-check-input' >
                                <label for="checkbox1">Remember me</label>
                            </div>
                            <div class="float-right">
                                <a href="{% url 'users:register' %}">Don't have an account?</a>
                            </div>
                        </div>
                        <div class="clearfix">
                            <button class="btn btn-primary float-right" type="submit" >Submit</button>
                        </div>
                    </form>
                    <div class="divider">
                        <div class="divider-text">OR</div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 text-center">
                            <a href="{% provider_login_url 'google' %}"><img  src="{% static 'dashboards/assets/images/google_signin.png' %}" width="40%" height="90%" alt="sign with Google"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    </div>
</body>
{% endblock %}

templates/users/staffs.html
{% extends "../includes/base_nav.html" %}
{% load static %}
{% block content %}
        <div id="main">
            <nav class="navbar navbar-header navbar-expand navbar-light">
                <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
                <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <div class="avatar mr-1">
                                    <img src="{% static 'dashboards/assets/images/avatar/avatar-s-1.png' %}" alt="" srcset="">
                                </div>
                                <div class="d-none d-md-block d-lg-inline-block">Hi, <span class="text-capitalize">{{user.username}}</span> </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i data-feather="user"></i> My Profile</a>
                                <!-- <a class="dropdown-item active" href="#"><i data-feather="mail"></i> Messages</a>
                                <a class="dropdown-item" href="#"><i data-feather="settings"></i> Settings</a> -->
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout'%}"><i data-feather="log-out"></i> Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            
<div class="main-content container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Staff Mambers</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class='breadcrumb-header'>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="btn btn-primary" href="{% url 'users:add-staff' %}">Add Staff</a></li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-header">
                
            </div>
            <div class="card-body">
                <table class='table table-responsive table-hover table-striped' id="table1">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for staff in staffs %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ staff.username }}</td>
                            <td>{{ staff.email }}</td>
                            <td>{{ staff.role }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="">View</a>
                                <a class="btn btn-success btn-xs" href="">Edit</a>
                                {% if staff.status == 1 %}
                                <a class="btn btn-warning btn-xs" href="deactivate-staff/{{staff.id}}">Deactivate</a>
                                {% endif %}
                                {% if staff.status == 0 %}
                                <a class="btn btn-danger btn-xs" href="delete-staff/{{staff.id}}">Delete</a>
                                {%  endif%}
                            </td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>

    </section>
</div>
        </div>
    </div>
</body>
{% endblock %}